spring:
  application:
    name: municipality-importer
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: municipality_management
  flyway:
    baseline-on-migrate: true
    schemas: municipality_management
    create-schemas: true
app:
  taskType: ${TASK_TYPE}
